### ISSUE TITLE
Constant Bitwarden crash messages in Safari

### ISSUE THREAD

**Issue by NWAjetjockey** [bitwarden/browser#1136]

**Comment by kspearrin** [comment]
may be related to https://github.com/bitwarden/browser/issues/1021

**Comment by NWAjetjockey** [comment]
Couldn’t find a #1021. Can you elaborate?

**Comment by The-Big-V** [comment]
Click here: #1021

**Comment by cscharf** [comment]
This should now be resolved with the new Bitwarden Web Extension (vs. App Extension), v1.49.0; Desktop version 1.25.0 (Mac App Store version only).

**Comment by andr984g** [comment]
> This should now be resolved with the new Bitwarden Web Extension (vs. App Extension), v1.49.0; Desktop version 1.25.0 (Mac App Store version only).

For me (on my M1 8GB MacBook Air), Safari still consistently crashes when clicking on certain images in Google Images. When Bitwarden is deactivated it doesn't happen. Here's a snippet from the crash info:

```
Application Specific Information:
Enabled App Extensions:
com.ritamsarmah.Accelerate.Extension (XXYXWGAW9Y) (Version: 31 - Display Version: 3.2.2) Accelerate
 
Enabled Web Extensions:
com.bitwarden.desktop.safari (LTZ2PFU5D6) (Version: 1.49.0 - Display Version: 1.49.0) Bitwarden - Free Password Manager
 
*** Terminating app due to uncaught exception 'NSInvalidArgumentException', reason: '<cert(0x132f31dc0) s: www.glasborde.dk i: RapidSSL RSA CA 2018> does not conform to NSSecureCoding'
terminating with uncaught exception of type NSException
abort() called

```

I don't really understand the difference between the Web Extension and the App that I have installed from the App Store. The info above says that Version 1.49.0 is running, but when I click 'about' while having the App opened, it says V1.25.0.

**Comment by mnguyenv** [comment]
I experience similar issue on macOS big sur 11.2.3. The only work around is I need to turn on "Ask" for other website in "Safari->Preference->Website->Extension->BitWarden"

**Comment by imrinzzzz** [comment]
> This should now be resolved with the new Bitwarden Web Extension (vs. App Extension), v1.49.0; Desktop version 1.25.0 (Mac App Store version only).

I'm using Bitwarden v 1.25.0 app extension on M1 Macbook (Big Sur 12). There are some sites that made my safari crashes as soon as I enter it. Just now I use Google to search images. When I click to see the image, my safari crashes. When I turn off Bitwarden, this doesn't happen.

**Comment by nikdoof** [comment]
Still experiencing this issue, Bitwarden 1.25.1, Extension 1.49.1, Safari 14.0.3, macOS 11.2.3, M1 Macbook.

[This link](https://www.google.com/imgres?imgurl=http%3A%2F%2Fwww.lvnsystems.com%2Fsitebuildercontent%2Fsitebuilderpictures%2FT5220.jpg&imgrefurl=http%3A%2F%2Fwww.lvnsystems.com%2Fcatalog%2Fi87.html&tbnid=1sr0nd8e-OwEpM&vet=12ahUKEwjQxsytlP3vAhUS-hoKHUFHDREQMygUegUIARD6Aw..i&docid=zsmYxv7KQ_TqMM&w=932&h=310&q=sun%20t5240&client=safari&ved=2ahUKEwjQxsytlP3vAhUS-hoKHUFHDREQMygUegUIARD6Aw) (which is a Google Images link) provided a consistent crash with Bitwarden enabled.

**Comment by andr984g** [comment]
> [This link](https://www.google.com/imgres?imgurl=http%3A%2F%2Fwww.lvnsystems.com%2Fsitebuildercontent%2Fsitebuilderpictures%2FT5220.jpg&imgrefurl=http%3A%2F%2Fwww.lvnsystems.com%2Fcatalog%2Fi87.html&tbnid=1sr0nd8e-OwEpM&vet=12ahUKEwjQxsytlP3vAhUS-hoKHUFHDREQMygUegUIARD6Aw..i&docid=zsmYxv7KQ_TqMM&w=932&h=310&q=sun%20t5240&client=safari&ved=2ahUKEwjQxsytlP3vAhUS-hoKHUFHDREQMygUegUIARD6Aw) (which is a Google Images link) provided a consistent crash with Bitwarden enabled.

Your link also consistently crashes my Safari with Bitwarden enabled. It would be interesting to learn if it is the same images on all systems.
[This link](https://www.google.com/imgres?imgurl=http%3A%2F%2Fcdn.shopify.com%2Fs%2Ffiles%2F1%2F1762%2F8771%2Fproducts%2FNew-works-sidebord-Florence-Side-Table_-metal-sort-roget-glas_grande.jpg%3Fv%3D1493822000&imgrefurl=https%3A%2F%2Fwww.roomformore.dk%2Fproducts%2Fnew-works-sidebord-florence-shelf-1&tbnid=U4VE7rK9jooqXM&vet=12ahUKEwi9lYb0mP3vAhWHuCoKHZMWA8gQMygAegQIARA6..i&docid=ZzV3IJDaj3cOuM&w=600&h=600&q=glassengebord&client=safari&ved=2ahUKEwi9lYb0mP3vAhWHuCoKHZMWA8gQMygAegQIARA6) used to do the same for me, but does it no longer.

**Comment by cscharf** [comment]
I believe the original issue was resolved. However would need @NWAjetjockey to confirm; closing this issue in the meantime.

As far as the crashing for certain images in Safari with the message presented, this is a known issue and would also make these reports a duplicate of https://github.com/bitwarden/browser/issues/1694, please #1694 for latest status, updates, etc.
