### ISSUE TITLE
Fill issues since last extension update - present on all browsers and systems

### ISSUE THREAD

**Issue by michaldybczak** [bitwarden/browser#408]
I switched to Bitwarden this week from LastPass, from few rasons:
- it's open source
- it's as good as LastPass, maybe better in some ways
- it's easy to import/export data, so switch was really smooth and easy (although there was some bug on secure notices where words got distorted, but that's out of scope of this issue).

I was impressed how it filled credentials although this feature was marked as experimental. Since today or yesterday, there was some update on plugins on all browsers. I could see that "Functions" changed into "Options" - good call. However, with the update browser extensions stopped working so well.

On sites that were working correctly, now I don't have auto-fill, moreover, there is no normal fill as well - I get error message, that I can't do it on that site and must copy/paste it manually.

Since that was no issue few days ago, something very bad has happened recently. I hope that my and maybe others feedback will let you know that some bug/regression was implemented in last extensions update.

The same problem is on all browsers like: Vivaldi, Chrome, Chromium, Firefox, on Windows and Linux.

Here is a bank site that I enter frequently (and LastPass had issues with it) which worked wonderfully with Bitwarden few days ago, now not anymore:

https://konto.bs-zywiec.pl/

There are two steps. If one is passed, in the second auto-fill works.

Unfortunately, there are more sites (with more traditional login page) that stopped working recently and they all cannot be filled and we need to manually copy/paste.

I may acknowledge that auto fill may not work or not work always - that's fine, but filling when clicking on correct card entry is not working - that's really bad. I hope, this will be fixed at some point.

If there is some additional info needed, I will gladly provide it, if I will be capable of it. I'm not IT person.

**Comment by kspearrin** [comment]
> Unfortunately, there are more sites (with more traditional login page) that stopped working recently and they all cannot be filled and we need to manually copy/paste.

Could you provide one of these sites so I can test against it? I haven't observed any new issues with autofilling yet.

**Comment by michaldybczak** [comment]
I saw them on other computer about 3 days ago, but don't remember exact addresses because it was not mine computer or system. So far, sites that I use seem to work aside the one I just gave you:

https://konto.bs-zywiec.pl/

Create some artificial credentials and try to reload site: it won't auto-fill. Then try to fill it manually from extension - you get error.

I don't know what is it about this site, like if it was cursed. It worked great with LastPass till some extension update. Your plugin worked well on it for few days and newest update broke it. And I log in there more then a dozen times a day. If it worked before, then it can work. I have no idea what's changed recently that it stopped.

**Comment by kspearrin** [comment]
I don't have proper credentials for this website. I won't be able to get pass the first username form.

**Comment by michaldybczak** [comment]
It's not about getting pass. If you do, then it works. There is just no proper auto-fill and fill and that can be tested without credentials.
Just use some made up ones. Proper form for this step are number 8 digits and then any password and see if you can fill it in any way.

**Comment by kspearrin** [comment]
There's no way we can autofill this website. They are intentionally trying to prevent people from doing things like autofilling. Look at the source code in your browser dev tools. There is JavaScript running on the page that is constantly changing the markup in real time. If this website used to work then it's because they added this craziness recently, not because we released an update.

**Comment by michaldybczak** [comment]
Oh, that's sad :(. This is a small bank but they have so tight security like a secret spaying agency :(.
Thanks for letting me know why this site is so difficult.

On the other hand, that may explain the behavior in lastpass since some time, it takes veeeery long time to fill it, it will eventually succeed, but it's not worth the wait (few minutes). My guess is, they had this counter measure since few months and just recently they disabled it for few days from some reason and turned it on again.

I guess that copying user name from plugin will have to suffice, it's more convenient then LastPass anyway.

Thanks.

**Comment by michaldybczak** [comment]
P.S. Just a thought - Is there a way to disable this java script but still have this site working ;)?

**Comment by kspearrin** [comment]
> P.S. Just a thought - Is there a way to disable this java script but still have this site working ;)?

I think the whole point is that they don't want you to...

**Comment by michaldybczak** [comment]
I think it's more to prevent robots, not valid users. I just found that I can disable javascript in firefox... We'll see. ;).
Thanks
